# Generated by Django 3.2.21 on 2023-09-11 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttester.site')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField()),
                ('assessment', models.CharField(choices=[('Pass', 'Response is valid'), ('Fail', 'Response is invalid'), ('None', 'Unsure of response validity')], default='None', max_length=12)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttester.query')),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttester.topic'),
        ),
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttester.query')),
            ],
        ),
    ]
