# Generated by Django 3.2.21 on 2023-09-12 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttester', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='assessment',
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Pass', 'Response is valid'), ('Fail', 'Response is invalid'), ('None', 'Unsure of response validity')], default='None', max_length=12)),
                ('expectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttester.expectation')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttester.response')),
            ],
        ),
    ]
