# Generated by Django 3.2.21 on 2023-09-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttester', '0002_add-assessment-model'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='prompt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
