# Generated by Django 3.2.21 on 2023-09-13 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttester', '0003_assessment_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expectation',
            old_name='title',
            new_name='value',
        ),
    ]
