# Generated by Django 3.2.21 on 2023-09-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttester', '0004_rename_title_expectation_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='mendable_api_key',
            field=models.CharField(default='60542854-5c02-4cd5-af72-0b58413682ed', max_length=200),
            preserve_default=False,
        ),
    ]
