# Generated by Django 3.2.21 on 2023-10-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttester', '0007_nullable_assessment_values_and_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='num_of_assessments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='value',
            field=models.CharField(blank=True, choices=[('Pass', 'Response is valid'), ('Fail', 'Response is invalid'), ('None', 'Unsure of response validity')], max_length=12, null=True),
        ),
    ]
